#ifndef VERSION_H
#define VERSION_H

#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#include "VersionNumber.h"

#define PONYTERRA_FILE_DESCRIPTION_STR "PonyTerra"
#define PONYTERRA_FILE_VERSION PONYTERRA_MAJOR, PONYTERRA_MINOR, PONYTERRA_REV, PONYTERRA_BUILD
#define PONYTERRA_FILE_VERSION_STR	STRINGIZE(PONYTERRA_MAJOR)		\
									"." STRINGIZE(PONYTERRA_MINOR)	\
									"." STRINGIZE(PONYTERRA_REV)		\
									"." STRINGIZE(PONYTERRA_BUILD)

#define PONYTERRA_PRODUCTNAME_STR "PonyTerra"
#define PONYTERRA_PRODUCT_VERSION PONYTERRA_FILE_VERSION
#define PONYTERRA_PRODUCT_VERSION_STR PONYTERRA_FILE_VERSION_STR
#define PONYTERRA_ORIGINAL_FILENAME_STR PONYTERRA_PRODUCTNAME_STR ""
#define PONYTERRA_INTERNAL_NAME_STR PONYTERRA_ORIGINAL_FILENAME_STR
#define PONYTERRA_COPYRIGHT_STR "Copyright (C) 2014 Gian Sass"

#ifdef DEBUG
#define PONYTERRA_VER_DEBUG VS_FF_DEBUG
#else
#define PONYTERRA_VER_DEBUG 0
#endif

#define PONYTERRA_FILEOS VOS__WINDOWS32
#define PONYTERRA_FILEFLAGS PONYTERRA_VER_DEBUG
#define PONYTERRA_FILETYPE VFT_APP

#endif
